title: Roy Manor
description: Data Analyst | Business Developer | Problem Solver
logo: assets/img/IMG_5389.jpeg
theme: jekyll-theme-minimal
show_downloads: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-commonmark-ghpages
  - jekyll-relative-links
markdown: CommonMarkGhPages
paginate: 10
